import type { CatalogProduct } from "@/components/blocks/catalog-browser";
import type { NewsCardProps } from "@/components/blocks/news-card";
import type { ProductCardProps } from "@/components/blocks/product-card";

/**
 * Sample catalog / news data taken from the home page mockup, used by the
 * /blocks preview. Real content will come from the CMS.
 */

export const products: ProductCardProps[] = [
  {
    name: "Наполнитель комкующийся Йо! TOFU Peach",
    href: "/catalog/tofu-peach",
    volume: "6 л / 2,5 кг",
    kind: "комкующийся",
    tint: "peach",
    image: { src: "/demo/pack-peach.jpeg", alt: "Йо! TOFU Peach" },
    badge: "Хит",
    tags: [
      { label: "Peach", tone: "peach", strong: true },
      { label: "Lavender", tone: "lavender" },
      { label: "Green tea", tone: "primary" },
    ],
    ctaLabel: "Подробнее",
  },
  {
    name: "Наполнитель силикагелевый Йо! Лаванда",
    href: "/catalog/lavender",
    volume: "12 л / 4,5 кг",
    kind: "силикагель",
    tint: "lavender",
    image: { src: "/demo/pack-lavender.jpeg", alt: "Йо! Лаванда" },
    tags: [
      { label: "12 л", tone: "lavender", strong: true },
      { label: "8 л", tone: "lavender" },
      { label: "4 л", tone: "lavender" },
    ],
    ctaLabel: "Подробнее",
  },
  {
    name: "Лакомства для собак Йо! Бычий корень",
    href: "/catalog/bull-root",
    volume: "100 г",
    kind: "сушёное",
    tint: "neutral",
    tags: [
      { label: "100 г", tone: "primary", strong: true },
      { label: "250 г", tone: "primary" },
    ],
    ctaLabel: "Подробнее",
  },
  {
    name: "Бальзам-кондиционер Йо! для всех типов шерсти",
    href: "/catalog/balm",
    volume: "500 мл",
    kind: "косметика",
    tint: "primary",
    tags: [
      { label: "500 мл", tone: "primary", strong: true },
      { label: "250 мл", tone: "primary" },
    ],
    ctaLabel: "Подробнее",
  },
];

export const news: NewsCardProps[] = [
  {
    title: "Йо! TOFU выходит в трёх ароматах",
    href: "/news/tofu-three-scents",
    date: "12 сентября 2026",
    dateTime: "2026-09-12",
    tint: "peach",
    readMoreLabel: "Читать",
  },
  {
    title: "Наполнитель-индикатор pH: первые тесты",
    href: "/news/ph-litter-tests",
    date: "28 августа 2026",
    dateTime: "2026-08-28",
    tint: "primary",
    readMoreLabel: "Читать",
  },
  {
    title: "«Йо!» на выставке зоотоваров в Минске",
    href: "/news/expo-minsk",
    date: "15 августа 2026",
    dateTime: "2026-08-15",
    tint: "lavender",
    readMoreLabel: "Читать",
  },
];

/**
 * Catalog listing (12 products from the Yo Catalog mockup). `animals` and
 * `type` are what the catalog filters match against.
 */
const photo = {
  peach: { src: "/demo/pack-peach.jpeg", alt: "Йо! TOFU Peach" },
  lavender: { src: "/demo/pack-lavender.jpeg", alt: "Йо! Лаванда" },
};

export const catalogProducts: CatalogProduct[] = [
  {
    slug: "tofu-peach",
    name: "Наполнитель комкующийся Йо! TOFU Peach",
    href: "/catalog/tofu-peach",
    animals: ["cats"],
    type: "litter",
    volume: "6 л / 2,5 кг",
    tint: "peach",
    tagTone: "peach",
    image: photo.peach,
  },
  {
    slug: "tofu-lavender",
    name: "Наполнитель комкующийся Йо! TOFU Lavender",
    href: "/catalog/tofu-lavender",
    animals: ["cats"],
    type: "litter",
    volume: "6 л / 2,5 кг",
    tint: "lavender",
    tagTone: "lavender",
    image: photo.lavender,
  },
  {
    slug: "tofu-green-tea",
    name: "Наполнитель комкующийся Йо! TOFU Green Tea",
    href: "/catalog/tofu-green-tea",
    animals: ["cats"],
    type: "litter",
    volume: "6 л / 2,5 кг",
    tint: "primary",
    tagTone: "primary",
    imageCaption: "упаковка",
  },
  {
    slug: "silica-lavender",
    name: "Наполнитель силикагелевый Йо! Лаванда",
    href: "/catalog/silica-lavender",
    animals: ["cats"],
    type: "litter",
    volume: "12 л / 4,5 кг",
    tint: "lavender",
    tagTone: "lavender",
    image: photo.lavender,
  },
  {
    slug: "wood-rodents",
    name: "Наполнитель древесный Йо! для грызунов",
    href: "/catalog/wood-rodents",
    animals: ["rodents"],
    type: "litter",
    volume: "5 л",
    tint: "primary",
    tagTone: "primary",
    imageCaption: "упаковка",
  },
  {
    slug: "bull-root",
    name: "Лакомства для собак Йо! Бычий корень",
    href: "/catalog/bull-root",
    animals: ["dogs"],
    type: "treats",
    volume: "100 г",
    tint: "neutral",
    tagTone: "primary",
    tagStrong: true,
    imageCaption: "упаковка",
  },
  {
    slug: "chicken-papaya",
    name: "Лакомства для кошек Йо! Курица и папайя",
    href: "/catalog/chicken-papaya",
    animals: ["cats"],
    type: "treats",
    volume: "50 г",
    tint: "peach",
    tagTone: "peach",
    tagStrong: true,
    imageCaption: "упаковка",
  },
  {
    slug: "dry-lamb-cats",
    name: "Корм сухой Йо! для кошек, ягнёнок",
    href: "/catalog/dry-lamb-cats",
    animals: ["cats"],
    type: "food",
    volume: "1,5 кг",
    tint: "lavender",
    tagTone: "lavender",
    tagStrong: true,
    imageCaption: "упаковка",
  },
  {
    slug: "dry-turkey-dogs",
    name: "Корм сухой Йо! для собак, индейка",
    href: "/catalog/dry-turkey-dogs",
    animals: ["dogs"],
    type: "food",
    volume: "2 кг",
    tint: "primary",
    tagTone: "primary",
    tagStrong: true,
    imageCaption: "упаковка",
  },
  {
    slug: "balm",
    name: "Бальзам-кондиционер Йо! для всех типов шерсти",
    href: "/catalog/balm",
    animals: ["cats", "dogs"],
    type: "care",
    volume: "500 мл",
    tint: "primary",
    tagTone: "primary",
    tagStrong: true,
    imageCaption: "упаковка",
  },
  {
    slug: "shampoo",
    name: "Шампунь гипоаллергенный Йо!",
    href: "/catalog/shampoo",
    animals: ["cats", "dogs"],
    type: "care",
    volume: "250 мл",
    tint: "lavender",
    tagTone: "lavender",
    tagStrong: true,
    imageCaption: "упаковка",
  },
  {
    slug: "odor-spray",
    name: "Спрей-нейтрализатор запаха Йо! для дома",
    href: "/catalog/odor-spray",
    animals: ["cats", "dogs", "rodents"],
    type: "home",
    volume: "300 мл",
    tint: "neutral",
    tagTone: "neutral",
    imageCaption: "упаковка",
  },
];
